# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 704920743c033952ffa72eff095383594dc4828aead4d7cb7a7ab4c6774ff14641d74921f274e90298080658b26369c975ddaaae3f50556ee4fbf0e936536cd8

test:
  secret_key_base: b96d6e801d70276b878a10f8ef29544447a16c257f076440c6a1d86381b9372605fcbf280d8805ca058e92656ff158fdb9c56a915201df7f3c685f82cf612afb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
